# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Disable vbguest plugin
    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false
    end

    config.vm.define "dev" do |dev|
        dev.vm.box = "ubuntu/bionic64"
        dev.vm.hostname = "dev"
        dev.vm.network "private_network", ip: "192.168.33.60"

        # Provider settings
        dev.vm.provider "virtualbox" do |vb|
            vb.name = 'dev'
            vb.gui = false
            vb.cpus = 2
            vb.memory = 2048
        end
    end

    class Username
        def to_s
            print "Username: "
            STDIN.gets.chomp
        end
    end

    class Password
        def to_s
            begin
            system 'stty -echo'
            print "Password: "
            pass = URI.escape(STDIN.gets.chomp)
            ensure
            system 'stty echo'
            end
            pass
        end
    end
    # To execute a shell script
    config.vm.provision "shell", env: {"username" => Username.new, "password" => Password.new}, path: "provision.sh"
end
